baseURL: https://andrew-houser.com/
languageCode: en-us
title: Andrew Houser
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# Search outputs
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

#googleAnalytics:

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Andrew Houser
  description: "My personal portfolio and blog."
  keywords: [Blog, Portfolio, PaperMod]
  author: Andrew Houser
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: false # to disable highlight.js
  #    # disableFingerprinting: true
  #    favicon: "<link / abs url>"
  #    favicon16x16: "<link / abs url>"
  #    favicon32x32: "<link / abs url>"
  #    apple_touch_icon: "<link / abs url>"
  #    safari_pinned_tab: "<link / abs url>"

  #  label:
  #    text: "Home"
  #    icon: /apple-touch-icon.png
  #    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Welcome to my website!"
    Content: I am a computer science student who enjoys system administration. This is where I document projects I'm working on and other things I want to share.

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/andrew-houser/"
    - name: github
      url: "https://github.com/andrewski04"

  #  analytics:
  #    google:
  #      SiteVerificationTag: "XYZabc"
  #    bing:
  #      SiteVerificationTag: "XYZabc"
  #    yandex:
  #      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  #editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 5
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 50
    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma

#markup:
#h#ighlight:
#noClasses: true
#anchorLineNos: true
#codeFences: true
#guessSyntax: true
# lineNos: true
#style: monokai
